### ISSUE TITLE
勉強会のやりたいことをまとめる 期限:  8/22

### ISSUE THREAD

**Issue by tanakahikari-pikka** [tanakahikari-pikka/hoge#2]

**Comment by 1l0-tk** [comment]
今回、短期間での開発およびチームメンバーが5 人ということもあり、
 Unit Test の作成およびCI 環境の作成をGithub Action でやりたい気持ち。

**Comment by minasehiro** [comment]
https://github.com/tanakahikari-pikka/hoge/issues/6 にてテンプレートに沿って作り直したのでクローズ
